### ISSUE TITLE
Sorting considered harmful

### ISSUE THREAD

**Issue by yacoob** [sixones/vitality#49]
If you enter a training plan, and then click on a column header to sort it, the original order of the skills is gone. I haven't found any way to undo this, and if sorting of the skill list created some unmet dependencies - well, it's up to the user to fix that. It's not exactly user friendly :(

**Comment by Bleyddyn** [comment]
Right click in the column header and choose the 'manual sort' option.

In the long run, all of Vitality really needs to support Undo/Redo.

And, in testing this I uncover a different bug, related to skill plan notes :(

**Comment by yacoob** [comment]
Ah, that's more like it. Yes, I had expected undo to work. :D Thanks for the help.

Should we close this bug?

**Comment by Bleyddyn** [comment]
Yes, I'll close it and open a new one for Undo/Redo, if there isn't one already.
